### ISSUE TITLE
Export => JOSM does nothing with lots of issues displayed

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-frontend#154]
Sometimes when doing Export => JOSM from the UI, nothing happens.  If you "zoom in" and get less issues, then it works.

Example of something I might be trying to export:

![Screenshot_20190730_162614](https://user-images.githubusercontent.com/26171839/62162715-d5298100-b2e6-11e9-9a95-93b6bcd023b7.png)

**Comment by drkludge** [comment]
[I can confirm the issue.  I was going to work on layer numbers that were not in the -5 to 5 range. ](http://osmose.openstreetmap.fr/en/map/#source=11452&limit=500&class=9006003&item=9006&zoom=8&lat=32.969&lon=-111.38&level=1%2C2%2C3&tags=&fixable=)  The error return by josm is 
`2019-08-08 05:34:49.208 INFO: RemoteControl received: GET /load_object?objects= HTTP/1.1
2019-08-08 05:34:49.214 WARNING: 'load_object' remote control request must have 'objects' parameter
2019-08-08 05:35:26.557 INFO: RemoteControl received: GET /load_object?objects= HTTP/1.1
2019-08-08 05:35:26.562 WARNING: 'load_object' remote control request must have 'objects' parameter`

**Comment by Korgi2** [comment]
I understand this is a bump of 16 months but I am having an unsolvable variant of this problem. Unlike the people above me, my Osmose will not export to a JOSM at any zoom level. 

![image](https://user-images.githubusercontent.com/61196219/100694693-96359080-335d-11eb-9a1b-993528b6488b.png)
This is the error I get in firefox console while attempting to export JOSM. I am not running in private mode and I have tried with adblockers off with no change. Really am wondering if its just broken or not.

**Comment by frodrigo** [comment]
@Korgi2 can you give details, osmose link to map, issue on the map...

**Comment by Korgi2** [comment]
> 
> 
> @Korgi2 can you give details, osmose link to map, issue on the map...

Alright sure.  I was running the osmose map based on my current issues and the link is https://osmose.openstreetmap.fr/en/map/#username=Korgi1&zoom=12&lat=13.4766&lon=504.818&item=9001&level=1%2C2%2C3&tags=&fixable=. I have had trouble with the Export function on the website from the moment I started using it with all files either not exporting when clicked or creating an empty file. I don't think the spot has to do with it as I cannot get the export function to work anywhere on the map and with any combination of selected issues. The only information I have that points to the issue is that image of my console. I know I'm saying very little in a lot of words but I honestly have no idea what the problem is or where to even look as I am not technically inclined.

**Comment by frodrigo** [comment]
You are in an invalid longitude, by circular earth multiple time
Valid URL
https://osmose.openstreetmap.fr/en/map/#username=Korgi1&zoom=11&lat=13.4503&lon=144.8571&item=xxxx&level=1%2C2%2C3&tags=&fixable=

I create a new issue for that #288

**Comment by Korgi2** [comment]
> 
> 
> You are in an invalid longitude, by circular earth multiple time
> Valid URL
> https://osmose.openstreetmap.fr/en/map/#username=Korgi1&zoom=11&lat=13.4503&lon=144.8571&item=xxxx&level=1%2C2%2C3&tags=&fixable=
> 
> I create a new issue for that #288

Wow that works like a charm thanks I didn't even notice the invalid lon in the url. Whats the best way to fix it myself if it happens again? As in, how do I make it acknowledge the correct lon or lat in the url bar?

**Comment by frodrigo** [comment]
No more issue now.
