### ISSUE TITLE
Marker-map offset when first opened

### ISSUE THREAD

**Issue by harry-wood** [osm-fr/osmose-frontend#366]
There's an incorrect offset in the positioning of all the issue markers when the map is first opened. It resolves itself after zooming

For example this red marker is suppose to point directly at the "20" number on the map. After zooming it jumps to the right place.

![animation](https://user-images.githubusercontent.com/227525/159682888-5a0d2055-48b3-4b53-a874-f689385e7058.gif)

The offset applies to all markers in the view, at all zoom-levels. The offset is always approx 35 pixels to the left and 35 pixels up, and this is the same pixel distance regardless of zoom level (perhaps something strange with leaflet "anchor" position handling)

**Comment by frodrigo** [comment]
The issue is know and more complex, time by time, a concurrency issue in JS happen. It results of shifted vector tile display.

It due to hackish usage by Osmose of low support of vector tile on leaflet.

Osmose use Leaflet.VectorGrid
https://github.com/Leaflet/Leaflet.VectorGrid

But Leaflet.VectorGrid does not support display outside of tile boundaries. Osmose do a hack on top of this to display Point of issue as non clipped marker.

**Comment by frodrigo** [comment]
Done with the switch to MapLibre.
