### ISSUE TITLE
errorlist "show more" lists same errors as its

### ISSUE THREAD

**Issue by dex2000** [osm-fr/osmose-frontend#38]
Steps to reproduce:
- Go to map: http://osmose.openstreetmap.fr/de/map/
- click on "overlapping building" http://osmose.openstreetmap.fr/de/errors/?item=0
- scroll down, click on "show more": http://osmose.openstreetmap.fr/de/errors/?item=0&limit=100

Same result.

Link on the map should be linked to limit=100 

OR 

first click on more should linked to limit=200 (or 500 or whatever)

**Comment by dex2000** [comment]
in additional to that: should it not be better to exclude the seen errors on "show more"? 
Like "show more" could list errors 100 to 200 not 1-200

**Comment by jocelynj** [comment]
You're right that the first click on "show some issues" should show more than issues than the one available by default. The code is currently as it is now, because there might be no errors shown on this page, for example when trying to get all errors from all countries.

Adding an offset to the URL should be very easy to add, and would allow to see following pages. The only issue is that there is no "ORDER BY" in the request - to make it faster -, so no guarantee is made by postgresql on the order of errors. Showing page 2 might not always return the same errors when reloaded.

**Comment by frodrigo** [comment]
I fix only the initial request.
As the content is non ordered random issues.
