### ISSUE TITLE
[Issues by user] Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by WK-GiHu** [osm-fr/osmose-frontend#45]
This error is already displayed on the second day. 
```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://osmose.openstreetmap.fr/en/byuser/?username=XXXXX' caused an error:
Internal Server Error
```
Is this a known issue?

**Comment by jocelynj** [comment]
Yes, thanks for the report. I have reverted commit 909fb1ba4eecee0f864d050d5e2ff4881e3b88bd temporarily, as it caused this problem.
@frodrigo page was failing because template views/errors/list.tpl needs a `query` parameter, which is not available when template is called from views/byuser/byuser.tpl.
