### ISSUE TITLE
'Typo in tag' detection not working

### ISSUE THREAD

**Issue by patka-123** [osm-fr/osmose-frontend#477]
I think there is something wrong going on with this detection. Both examples are tagged correctly but Osmose somehow shows that there are errors. The displayed typos are not present in the tags. (I didn't know if I should report this bug here or in the backend. Let me know if this is the wrong place.)

**Example 1:**
For [this way](https://www.openstreetmap.org/way/825952717) I get the following error:
```
lock:material` is more common than `block:material`, is `block:material` a typo?
```

**Example 2:**
For [this node](https://www.openstreetmap.org/node/494157348) I get the following error:
```
post:coffee is more common than cost:coffee, is cost:coffee a typo?
```

**Comment by Famlam** [comment]
This detection is based on documented keys and similarity to documented keys. The detection does not look at the context, just to written similarity. 
Neither `cost:coffee` (208 uses worldwide) nor `block:material` (58 uses worldwide) are established, documented tags. Hence, they're marked as being likely typos as they're very similar to common tags (`lock` and `post`). 
If however I missed a wiki page where they are documented for some time, please let us know. 

I think the common tag for prices is `charge` (although I wouldn't tag coffee prices as the price may change by the day, but that's your call :) ).
And the common tag for materials is just `material`. (For your bollard, I suspect you should retag it as `barrier=block + material=*`, rather than `barrier=bollard + bollard:type=block + block:material=*`).

P.s. backend would indeed have been the correct place ;)
