### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by XioNoX** [osm-fr/osmose-frontend#485]
Hi,

Not sure if it's related to #481 but also is different from #326.

For an unknown reason, I got logged out my OSM account on https://osmose.openstreetmap.fr/ 
Clicking on the "login" link, redirects me to the correct `https://www.openstreetmap.org/oauth/authorize?oauth_token=XXXX` page asking the usual:
> The application [Osmose](http://osmose.openstreetmap.fr/) is requesting access to your account, [XioNoX](https://www.openstreetmap.org/user/XioNoX). Please check whether you would like the application to have the following capabilities. You may choose as many or as few as you like.

After clicking on "Grant Access" (with all the boxes checked). I'm redirected back to https://osmose.openstreetmap.fr/ but still not logged in.

I tried it in a different browser, cleared cookies, cache, but nothing solved the issue. The Firefox console doesn't show any specific error.
Anything I can do to help troubleshot it ?

Thanks

**Comment by frodrigo** [comment]
Logging ported to OAuth.

**Comment by nleanba** [comment]
I have the same issue.

1. I click "Login" on https://osmose.openstreetmap.fr/en/map/
2. I get to the OSM authorize page, where I click "Authorize"
3. then it goes back to osmose but still not logged in.

Sometimes, after step 1, I also get to https://osmose.openstreetmap.fr/en/login and it only shows "500 Internal Server Error" on an otherwise blank page
